services:
  unyx-web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: unyx-web

    restart: unless-stopped

    expose:
      - "80"

    labels:
      - "traefik.enable=true"

      # Router principal
      - "traefik.http.routers.unyx-web.rule=Host(`unyxsolutions.com`) || Host(`www.unyxsolutions.com`)"

      # HTTPS
      - "traefik.http.routers.unyx-web.entrypoints=websecure"
      - "traefik.http.routers.unyx-web.tls=true"
      - "traefik.http.routers.unyx-web.tls.certresolver=letsencrypt"

      # Puerto interno de Nginx
      - "traefik.http.services.unyx-web.loadbalancer.server.port=80"

    networks:
      - unyx-network

networks:
  unyx-network:
    name: unyx-network
